---
abstract: 'install the C libxml2 library on your system'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  File::Which: '0'
configure_requires:
  Alien::Base: '0.001'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-LibXML
provides:
  Alien::LibXML:
    file: lib/Alien/LibXML.pm
    version: '0.003'
requires:
  Alien::Base: '0.005'
  File::ShareDir: '1.00'
  perl: v5.8.9
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Alien-LibXML
  homepage: https://metacpan.org/release/Alien-LibXML
  license: http://www.opensource.org/licenses/mit-license.php
  repository: git://github.com/tobyink/p5-alien-libxml.git
version: '0.003'
x_contributors:
  - 'Graham Ollis (PLICEASE) <plicease@cpan.org>'
